-- Retired legacy migration.
--
-- The original version created public.users with TEXT IDs, which conflicts with
-- the canonical Neon Auth identity table. The active, UUID-compatible migration
-- is domains/user/migrations/rbac.migration.ts and is run by scripts/migrate.ts.
-- Do not create an application user table.
